version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
      - run:
          command: ./gradlew resolveDependencies
          working_directory: gradle-require-dependency-compliance-plugin
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
      - run: 
          command: ./gradlew test
          working_directory: gradle-require-dependency-compliance-plugin
      - store_test_results:
          path: gradle-require-dependency-compliance-plugin/build/test-results
      - store_artifacts:
          path: gradle-require-dependency-compliance-plugin/build/test-results
      - run: 
          command: ./gradlew build
          working_directory: gradle-require-dependency-compliance-plugin
      - store_artifacts:
          path: gradle-require-dependency-compliance-plugin/build/libs
      - persist_to_workspace:
          root: .
          paths: ./*
  sonarqube:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: Set PR number (fix for missing envorinment variable)
          command: |
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
              echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
              echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
              source $BASH_ENV
              echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
      - run:
          command: ./gradlew sonarqube
          working_directory: gradle-require-dependency-compliance-plugin
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
      - run:
          command: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
          working_directory: gradle-require-dependency-compliance-plugin
  regression-4.8:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
    - run:
        command: ./gradlew check --project-prop gradleVersion=4.8
        working_directory: gradle-require-dependency-compliance-plugin
  regression-4.8.1:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
    - run:
        command: ./gradlew check --project-prop gradleVersion=4.8.1
        working_directory: gradle-require-dependency-compliance-plugin
  regression-4.9:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "gradle-require-dependency-compliance-plugin/build.gradle" }}
    - run:
        command: ./gradlew check --project-prop gradleVersion=4.9
        working_directory: gradle-require-dependency-compliance-plugin
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - hold
      - sonarqube:
          requires:
            - build
      - regression-4.8:
          requires:
            - build
      - regression-4.8.1:
          requires:
          - build
      - regression-4.9:
          requires:
            - build